[package]
name = "rust_hello"
version = "0.1.0"
edition = "2018"

[build-dependencies]
kernel_path = "0.1"

[dependencies]
kernel = { path = "kernel_link" } # This will be set by the build script

[build]
build = "build.rs"
